# Default values for mutator helm
appName: k8s-webhook-injector # application name
mountPath: /ssl

# Values for mutator-deployment
contName: k8s-webhook-injector-ws # name of the container
image: mutator:latest # image name
pullPolicy: Never # pull policy for image

containerPort: 8443 # port for the container

replicaCount: 1 # number of replicas

# Values for mutator-ConfigMap

confName: ssl-k8s-webhook-injector # configuration name

# TODO should be removed after implementation of helm based certificate generation
serverCrt: "your certificate" # ssl key
serverKey: "your key" # ssl certificate

# cert and key file names referenced to corresponding config map keys with certificate and key
serverCrtFile: server.crt
serverKeyFile: server.key

# Values for mutator-configuration
sideCarConfig: /etc/sidecar/config/monitor-sidecar-config.yaml

caBundle: "your CA certificate" # caBundle value

path: "/mutate"

# Values for mutator-service
port: 443 # port of this service
targetPort: 8443 # port to accept traffic on

injectionNamespaces:
  - default

sideCar:
  image: hasher:latest
  secretName: db-secret-database-to-integrity-sum
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "150m"
  db:
    # db name usually passed through ENVs DB_NAME, DB_HOST, DB_PORT,but could be defined here as well
    host: db-postgresql
    port: 5432
    name: ""
  durationTime: 30s # may be pollInterval will be more descriptive
  workers: 4
  procDir: /proc
  algorithm: SHA256
