# Default values for mutator helm
appName: k8s-webhook-injector # application name
mountPath: /ssl

# Values for mutator-deployment
contName: k8s-webhook-injector-ws # name of the container
image: mutator:latest # image name
pullPolicy: Never # pull policy for image

containerPort: 8443 # port for the container

replicaCount: 1 # number of replicas

# Values for mutator-ConfigMap

confName: ssl-k8s-webhook-injector # configuration name

serverCrt: "your certificate" # ssl key
serverKey: "your key" # ssl certificate

# Values for mutator-configuration

namespaceConf: default # namespace of cluster

caBundle: "your CA certificate" # caBundle value

path: "/mutate"

# Values for mutator-service

namespaceService: default # namespace of cluster

port: 443 # port of this service
targetPort: 8443 # port to accept traffic on

sideCar:
  secretName: db-secret-database-to-integrity-sum
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "150m"
  db:
    host: localhost
    port: 5432
    name: "hashsums"
  durationTime: 30 # may be pollInterval will be more descriptive
  workers: 4
  procDir: /proc
  algorithm: SHA256
